parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true

extends: ["prettier", "htmlacademy/node"]

plugins: ["prettier"]

rules:
  "prettier/prettier": "error"
  object-curly-spacing: "off"
  indent: "off"
