parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true
  "jest/globals": true

extends: ["prettier", "htmlacademy/node"]

plugins: ["prettier", "jest"]

rules:
  "prettier/prettier": "error"
  object-curly-spacing: "off"
  indent: "off"
