'use strict';

module.exports.EXIT_CODE = {
  SUCCESS: 0,
  UNCAUGHT_FATAL_EXCEPTION: 1
};

module.exports.HTTP_CODE = {
  OK: 200,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  FORBIDDEN: 403,
  UNAUTHORIZED: 401,
};
